config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'ingredients/search', to: 'ingredients#search', as: :ingredient_search
  get 'counties/search', to: 'counties#search', as: :county_search
  resources :counties, only: [:show, :index] do
    resources :ingredients, only: [:index]
  end
  resources :food_groups, only: [:show, :index]
  resources :ingredients, except: [:index] do
    resources :recipes, only: [:index]
  end
  resources :recipes, only: [:show]
  resources :ingredient_at_vendors
  resources :ingredient_seasons, only: [:index, :show]
  resources :review, except: [:edit, :update]
  resources :users
  resources :vendor


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/county.rb
class County < ApplicationRecord
  has_many :users
  has_many :vendors
  has_many :ingredient_seasons
  has_many :ingredients, through: :ingredient_seasons
end

app/models/food_group.rb
class FoodGroup < ApplicationRecord
  has_many :ingredients
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :food_group

  has_many :ingredient_seasons
  has_many :ingredient_at_vendors
  has_many :recipes
  has_many :vendors, through: :ingredient_at_vendors

  mount_uploader :thumbnail_picture, PhotoUploader
  mount_uploader :background_picture, PhotoUploader

  def in_season?
    season = self.ingredient_seasons.first
    current_month = Date.today
    date_range = (season.start..season.end)
    date_range.include? current_month
  end

end

app/models/ingredient_at_vendor.rb
class IngredientAtVendor < ApplicationRecord
  belongs_to :vendor
  belongs_to :ingredient
end

app/models/ingredient_season.rb
class IngredientSeason < ApplicationRecord
  belongs_to :ingredient
  belongs_to :county
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :ingredient

  mount_uploader :thumbnail_picture, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :vendor
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :county, required: false
end

app/models/vendor.rb
class Vendor < ApplicationRecord
  belongs_to :county

  has_many :ingredient_at_vendors
  has_many :ingredients, through: :ingredient_at_vendors

  mount_uploader :picture, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/counties_controller.rb
class CountiesController < ApplicationController
  def search
    @county = County.find_by(name: params[:query].capitalize)
    if @county
      current_user.county_id = @county.id if current_user
      current_user.save
      redirect_to county_path(@county)
    else
      redirect_to root_path
    end
  end

  def show
    @county = County.find(params[:id])
  end

  def index
    @counties = County.all
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def search
    @ingredient = Ingredient.find_by(name: params[:query].split.map(&:capitalize).join(' '))
    if @ingredient
      redirect_to ingredient_path(@ingredient)
    else
      redirect_to county_path(current_user.county)
    end
  end

  def index
    @county = County.find(params[:county_id])
    @food_group = FoodGroup.find_by(name: params[:food_group])
    ingr = @county.ingredients.where(food_group: @food_group)
    @ingredients = []
    ingr.each do |ingredient|
      @ingredients << ingredient if ingredient.in_season?
    end
  end

  def show
    @ingredient = Ingredient.find(params[:id])
    in_season = @ingredient.in_season?

    flash.now[:alert] = "" if !@ingredient.in_season? && @ingredient

    @vendors = Vendor.where(county: current_user.county)
    if in_season
    @markers = @vendors.map do |vendor|
      {
        lat: vendor.latitude,
        lng: vendor.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { vendor: vendor })
      }
    end
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
    @counties = County.all
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController

  def index
    @ingredient = Ingredient.find(params[:ingredient_id])
    @recipes = @ingredient.recipes
  end

  def show
    @recipe = Recipe.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/counties/index.html.erb
<p>this is the index page</p>

app/views/counties/show.html.erb
<div class="show-county-background">
<div class="background-sussex">
  <div class="county-name-and-search">
  <h1><%= @county.name %></h1>
  <div class = 'tagline-container'>
   <h2> With the arable land of the weald, prime pasture along the length of the South Downs, and more than 80 miles of coastline, eating local certainly won’t be a chore. . . </h2>
 </div>
 <%= form_tag ingredient_search_path, class: "search" , method: :get do %>
  <div class="search-and-submit-box">
  <%= text_field_tag :query, nil, class: "form-control-home", placeholder: "Find seasonal ingredients"%>
  <%= button_tag(type: "submit", class: "search-button") do %>
    <div>Ask Freya!</div>
  <% end %>
  </div>
  <% end %>

</div>
<div class="county-show-card-box">

<div class="food-group-icons floating">
<%= link_to county_ingredients_path(@county, food_group: "Meat") do %>
<%= image_tag('cartoon-meat.png') %>
<% end %>
</div>

<div class="food-group-icons less-floating">
<%= link_to county_ingredients_path(@county, food_group: "Vegetable") do %>
<%= image_tag('cartoon-vegetable.png') %>
<% end %>
</div>

<div class="food-group-icons floating">
<%= link_to county_ingredients_path(@county, food_group: "Fish") do %>
<%= image_tag('cartoon-fish.png') %>
<% end %>
</div>

<div class="food-group-icons less-floating">
<%= link_to county_ingredients_path(@county, food_group: "Fruit") do %>
<%= image_tag('cartoon-fruit.png') %>
<% end %>
</div>

</div>

</div>

app/views/ingredients/_info_window.html.erb
<a href="<%= vendor.link %>" target="_blank">
<h1><%= vendor.name %></h1>
</a>
<p><%= vendor.address %></p>
<a href="<%= vendor.link %>" target="_blank">
<%= cl_image_tag vendor.picture, alt: "alttext", :size => '200x200'%>

</a>

app/views/ingredients/home.html.erb
home.html.erb

app/views/ingredients/index.html.erb
<div class= 'textured-background'>
<% if params[:food_group] == "Fish" %>
<div class="top-banner-card fish-position" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path 'fish-background.jpg' %>')">
  <h1>
  FISH
  </h1>
</div>


<% elsif params[:food_group] == "Meat" %>
<div class="top-banner-card meat-position" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path 'meat-background.jpg' %>')">
  <h1>
  MEAT
  </h1>
</div>
<% elsif params[:food_group] == "Vegetable" %>
<div class="top-banner-card  vegetable-position" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path 'vegetable-background-2.jpg' %>')">
  <h1>
  VEGETABLES
  </h1>
</div>
<% else params[:food_group] == "Fruit" %>
<div class="top-banner-card fruit-position" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= image_path 'fruit-background.jpg' %>')">
  <h1>
  FRUIT
  </h1>
</div>
<% end %>

<% months = ['January','February','March','April','May','June','July','August','September','October','November','December'] %>
<% county = County.find_by id: params[:county_id] %>
<% if Date.today.day > 15 %>
<% stage = "late" %>
<% else %>
<% stage = "early" %>
<% end %>

<div class='container index-container'>

<h1 class='heading-container'> Available in <%= county.name %> in <%= stage %> <%= months[Date.today.month.to_i - 1] %></h1>

<div class="cards">

<% current_time = Time.now %>
 <% @ingredients.each do |ingredient| %>
 <div style= "text-decoration: none">
   <%= link_to ingredient_path(ingredient), {:style=>'text-decoration: none'} do %>
    <div class="card veg-card-long">
      <div class = "card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= ingredient.thumbnail_picture %>)">
      </div>
      <div class= "ingredient-card-info">
        <div class = "info-header" >
        <h2> <%= ingredient.name %> </h2>
         <% ingredient_season = IngredientSeason.where({county: current_user.county, ingredient: ingredient}).first %>
        <% months = ['January', 'February', 'March', 'April', 'May', 'June', 'July','August','September','October','November','December'] %>
        <%= months[ingredient_season.start.month - 1] %> - <%= months[ingredient_season.end.month- 1]  %>
        </div>
        <h3> <%= ingredient.binomial %> </h3>

      </div>
  </div>
  <%end%>
  </div>
<% end %>
</div>




</div>

</div>

app/views/ingredients/show.html.erb
<div class="show-background-image-ingredient" style="background-image:url('<%= cl_image_path @ingredient.background_picture%>')">
  <div>
  <div class="white-border-container">
    <div class="show-container">
      <div class="show-container-left">
                <div class="border-radius-description">
        <div class="ingredient-name">
          <h1><%=@ingredient.name%></h1>
          <br>
          <div class="binomial-name">
            <h3><%=@ingredient.binomial%></h3>
          </div>
        </div>
        <div class="ingredient-card-show">
          <div><p><%=@ingredient.description.split(" Choose")[0]%></p>
            <p><%="Choose #{@ingredient.description.split(" Choose")[1]}" unless @ingredient.description.split(" Choose")[1].nil?%></p></div>
        </div>
      </div>
      </div>
      <div class="show-container-right">
        <div
          id="map"
          style="width: 100%;
          height: 525px;"
          data-markers='<%= @markers.to_json %>';
          data-mapbox-api-key= <%= ENV['MAPBOX_API_KEY']  %>
        >
<%= link_to ingredient_recipes_path(@ingredient) do %>
<div class="box-one"><h3>Recipes!</h3></div></div>

      </div>
      <% end %>
    </div>
<% ingredient_season = IngredientSeason.where({ county: current_user.county, ingredient: @ingredient }).first  %>



<div class="months-container">

    <div class="month-red">
 <div class="month-title"><p>Jan</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 1, 1) %>
  <% beginning2 = Date.new(2020, 1, 1) %>


  <% 31.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
          <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>


      <div class="month-red">
<div class="month-title"><p>Feb</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 2, 1) %>
  <% beginning2 = Date.new(2020, 2, 1) %>


  <% 28.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
          <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>


      <div class="month-red">
<div class="month-title"><p>Mar</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 3, 1) %>
  <% beginning2 = Date.new(2020, 3, 1) %>


  <% 31.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
          <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>


      <div class="month-red">
<div class="month-title"><p>Apr</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 4, 1) %>
  <% beginning2 = Date.new(2020, 4, 1) %>


  <% 30.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
          <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>


    <div class="month-red">
    <div class="month-title"><p>May</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 5, 1) %>
  <% beginning2 = Date.new(2020, 5, 1) %>


  <% 31.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
          <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>

      <div class="month-red">
 <div class="month-title"><p>Jun</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 6, 1) %>
  <% beginning2 = Date.new(2020, 6, 1) %>


  <% 30.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
    <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>

      <div class="month-red">
 <div class="month-title"><p>Jul</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 7, 1) %>
  <% beginning2 = Date.new(2020, 7, 1) %>


  <% 31.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
          <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>

       <div class="month-red">
 <div class="month-title"><p>Aug</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 8, 1) %>
  <% beginning2 = Date.new(2020, 8, 1) %>


  <% 31.times do %>

    <div class="<% if beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
          <% elsif tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>

    <div class="month-red">
 <div class="month-title"><p>Sept</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 9, 1) %>
  <% beginning2 = Date.new(2020, 9, 1) %>


  <% 30.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
          <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>

      <div class="month-red">
 <div class="month-title"><p>Oct</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 10, 1) %>
  <% beginning2 = Date.new(2020, 10, 1) %>


  <% 31.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
          <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>

     <div class="month-red">
 <div class="month-title"><p>Nov</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 11, 1) %>
  <% beginning2 = Date.new(2020, 11, 1) %>


  <% 30.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
          <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>

    <div class="month-red">
 <div class="month-title"><p>Dec</p></div>
  <% tiny_array = (ingredient_season.start..ingredient_season.end) %>
  <% beginning = Date.new(2019, 12, 1) %>
  <% beginning2 = Date.new(2020, 12, 1) %>


  <% 31.times do %>

    <div class="<% if tiny_array.include?(beginning) || tiny_array.include?(beginning2) %>
      <%= "tiny-date" %>
          <% elsif beginning == Date.today || beginning2 == Date.today %>
      <%= "tiny-today" %>
    <% else  %>
      <%= "tiny-date-red" %>
    <% end %>
    ">
    </div>

  <% beginning += 1 %>
  <% beginning2 += 1 %>
  <% end %>

  </div>

</div>



  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag asset_path('logo_red.ico') %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Freya</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="big-picture">
<br>
<br>
<br>
<br>
<br>
<br>

<div class="home-main-div">
<div class="logo-box">
 <%= image_tag "Freya_Logo_Orange-crop.png", alt: "alttext", :size => '230x230'%>
</div>
<div class="title-box-home">
  <br>
<h1>Freya</h1>
</div>
<h2 class='tagline'> Find fresh with Freya </h2>
  <%= form_tag county_search_path, class: "search" , method: :get do %>
  <div class="search-and-submit-box">
  <%= text_field_tag :query, nil, class: "form-control-home search-text", placeholder: "Enter your county"%>
  <%= button_tag(type: "submit", class: "search-button") do %>
    <div>Search</div>
  <% end %>

  </div>
<% end %>
</div>
</div>

app/views/recipes/index.html.erb
<div class= 'textured-background'>
<div class="top-banner-card fish-position" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= @ingredient.background_picture %>')">
  <h1>
  <%= @ingredient.name %> Recipes
  </h1>
</div>

<div class='container index-container extra-pad'>

<!-- <h1 class='heading-container'> <%= @ingredient.name %></h1> -->
<a name="recipes"></a>
<div class="cards">

 <% @recipes.each do |recipe| %>
 <div style= "text-decoration: none">
   <%= link_to recipe_path(recipe), {:style=>'text-decoration: none'} do %>
    <div class="card recipe-card-long">
      <div class = "card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= recipe.thumbnail_picture %>)">
      </div>
      <div class= "ingredient-card-info info-long">
        <h2> <%= recipe.name %> </h2>
        <% hours = recipe.hours_preparation %>
        <% if recipe.hours_preparation >= 1 %>
          <h3> <strong> <%= hours %> </strong> hours preparation </h3>
        <% else %>
        <h3> <strong> <%= (60 * hours).round %> </strong> minutes preparation </h3>
        <% end %>

      </div>
  </div>
  <%end%>
  </div>
<% end %>
</div>




</div>

</div>

app/views/recipes/show.html.erb
<div class="recipe-background" style="height: 104vh;">
  <div>
    <br>
    <br>
    <br>
    <div class="white-border-container" style="height: 670px;">
    <div class="show-container-recipe">
      <div class="show-container-left-recipe">
                <div class="border-radius-description-recipe">
        <div class="recipe-name">
          <h1><%=@recipe.name%></h1>
          <br>
         <!--  <div class="binomial-name">
            <h3> Serves <%=@recipe.serves%> people</h3>
          </div> -->
        </div>
        <div class="recipe-card-show">
          <div class="show-container-left">
          <h3><%=@recipe.description%></h3>
                     <%@recipe.shopping_list.split(';;;').each do |item| %>
                     <p style="margin-top: 0px;"> <%= item %> </p>
                      <% end %>
                      <br>
          <p style="margin-bottom: 5px;"> <strong> Instructions </strong> </p>
                               <%@recipe.instructions.split(',;;;').each do |item| %>
                     <p style="margin-top: 0px;"> <%= item %> </p>
                      <% end %>
        </div>
        </div>
      </div>
      </div>
      <div class="show-container-right-recipe" style="background-image:url('<%= @recipe.thumbnail_picture%>')">
<div class="recipe-button-holder">
  <a href="../ingredients/<%= @recipe.ingredient_id %>/recipes#recipes">
<div class="box-two-recipe"><h3>View more recipes</h3>
</div>
</a>
<%= link_to ingredient_path(@recipe.ingredient) do %>
<div class="box-one-recipe"><h3>Ingredient page</h3></div></div>
</div>
<% end %>
<!--         <div class="container-for-both-buttons">
          <div class="box-one"><p>Near me</p></div>
          <div class="box-two"><p>Recipes!</p></div>
        </div> -->
      </div>
<!--         <div class="container-for-both-buttons">
          <div class="box-one"><p>Near me</p></div>
          <div class="box-two"><p>Recipes!</p></div>
        </div> -->
      </div>
    </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
   <div class="flash flash-danger alert alert-dismissible fade show floating-flash" role="alert">
  <div class= 'flash-container' >
  <div style = 'text-align:right' data-dismiss="alert" aria-label="Close">
    <i class="fas fa-times"></i>
  </div>
  <div class = 'oops' style = 'text-align:center'><strong>Oops!</strong> </div>
  <div class="logo-box-flash" style = 'text-align:center'>
    <%= image_tag "logo_red.png", alt: "alttext", :size => '230x230'%>
  </div>
  <% ingr = @ingredient.name.downcase if @ingredient %>
  <% ingredient_season = IngredientSeason.where({ county: current_user.county, ingredient: @ingredient }).first if @ingredient %>
  <% ingredient_season_month = ingredient_season.start if @ingredient %>
  <% months = ['January','February','March','April','May','June','July','August','September','October','November','December'] %>
  <div style = 'text-align:center'>It seems <%= ingr.pluralize if @ingredient %> aren't in season until <%= months[ingredient_season_month.month - 1] if @ingredient %>. Why not ask <span class='oops-f'>Freya</span> for something fresh and local.</div>
  </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to  root_path, class: "navbar-brand" do %>
    <%= image_tag "Freya_Logo_Orange-crop.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "My county", county_path(current_user.county), class: "nav-link"  unless current_user.county.nil? %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "avatar.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "My page", user_path(current_user), class: "dropdown-item"%>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/show.html.erb
<p>welcome to <%=@user.email=%>'s page!</p>